// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DamageType = "piercing" | "bludgeoning" | "slashing" | "cold" | "fire" | "lightning" | "thunder" | "poison" | "acid" | "necrotic" | "radiant" | "force" | "psychic";