// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageType } from "./DamageType";
import type { Dice } from "./Dice";

export type SpellDice = { dice: Dice, base: number, scaling: number, damageType: DamageType | null, };