// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellDice } from "./SpellDice";

export type SpellView = { id: bigint, name: string, iconUrl: string, level: string, school: string, rangeArea: string, attackSave: string, components: string, castTime: string, duration: string, damageEffect: string, dice: Array<SpellDice>, hasMultipleEffects: boolean, };